### PR TITLE
added few more randomizations

### PR DESCRIPTION
**Pull request by iamalsaher**
added the randomizations approved in apkwash script

### CODE REVIEW

**Review by jbreed — APPROVED** [review]
Looks good to me. Were you getting the Avast flags of potentially unwanted program before adding these randomization additions?

**Comment by iamalsaher** [comment]
Yup, but I can't​ test the new commits right now

**Comment by jbreed** [comment]
@iamalsaher Ok sounds good. I am thinking it is probably due to the amount of permissions. To test, remove all .smali payload files, manually rebuild with apktool (see script for example), then test again to see if it flags. If it does, then start over by leaving the .smali files in place and just commenting out all extra permissions added via the script.

**Comment by jbreed** [comment]
I noticed the Avast potentially unwanted program flag after I ran a payload generated with the updates. I don't think I used Avast before, but now that there is something else tipped off it will bug me until I find it. I just don't have the time right now to tinker with it.

**Comment by iamalsaher** [comment]
I will give it a go

**Pull request merged**
